version: "3.8"

services:
  tempo:
    image: grafana/tempo:latest
    command: -config.file=/etc/tempo-local.yaml
    ports:
      - "14268:14268"
    volumes:
      - type: bind
        source: ./files/tempo-local.yaml
        target: /etc/tempo-local.yaml
    networks:
      - oteldemo

  tempo-query:
    image: grafana/tempo-query:latest
    command: --grpc-storage-plugin.configuration-file=/etc/tempo-query.yaml
    ports:
      - "16686:16686"
    volumes:
      - type: bind
        source: ./files/tempo-query.yaml
        target: /etc/tempo-query.yaml
    depends_on:
      - tempo
    networks:
      - oteldemo

  backend:
    build:
      dockerfile: Dockerfile.backend
      context: .
    environment:
      BACKEND_LISTEN: 0.0.0.0:80
      JAEGER_ENDPOINT: http://tempo:14268/api/traces
    ports:
      - "8888:80"
    depends_on:
      - tempo
    networks:
      - oteldemo

  frontend:
    build:
      dockerfile: Dockerfile.frontend
      context: .
    environment:
      FRONTEND_LISTEN: 0.0.0.0:80
      JAEGER_ENDPOINT: http://tempo:14268/api/traces
      BACKEND_ENDPOINT: http://backend/main
    ports:
      - "8080:80"
    depends_on:
      - tempo
      - backend
    networks:
      - oteldemo

networks:
  oteldemo:
