FROM golang AS builder

COPY . /app

WORKDIR /app

RUN go mod vendor
RUN CGO_ENABLED=0 go build -ldflags="-s -w -X main.build=${DOCKER_TAG:-${SOURCE_COMMIT:-local}}" -o /backend ./cmd/backend/main.go


FROM scratch

COPY --from=builder /backend /

EXPOSE 8888

ENTRYPOINT ["/backend"]
