apiVersion: v1
kind: Service
metadata:
  name: {{ include "this.fullname" . }}
  labels:
    {{- include "this.labels" . | nindent 4 }}
    {{- if .Values.service.labels }}{{ "\n" }}
      {{- tpl (toYaml .Values.service.labels | indent 4) . }}
    {{- end }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- tpl (toYaml .Values.service.annotations) . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http-metrics
      protocol: TCP
      name: http
  selector:
    {{- include "this.selectorLabels" . | nindent 4 }}
