apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-demo-github
  namespace: argocd
spec:
  project: otel-demo
  source:
    repoURL: https://github.com/jtyr/otel-demo.git
    targetRevision: HEAD
    path: argocd
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
