apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  namespace: argocd
spec:
  project: otel-demo
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: promtail
    targetRevision: "*"
    helm:
      values: |
        config:
          lokiAddress: http://loki:3100/loki/api/v1/push
  destination:
    server: https://kubernetes.default.svc
    namespace: grafanalabs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
