apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
spec:
  project: otel-demo
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: tempo
    targetRevision: "*"
  destination:
    server: https://kubernetes.default.svc
    namespace: grafanalabs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
